# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountryPOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Google-Mobile-Ads-SDK'

  # Pods for CountryPOS

  target 'CountryPOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
